# Generated by Django 3.2.3 on 2021-05-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_category_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Service')),
                ('price', models.FloatField(default=0.0, verbose_name='Item Price Per Unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Servicess',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
    ]
