# Generated by Django 3.2.3 on 2021-05-26 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210526_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='account.item'),
        ),
    ]
