# Generated by Django 3.2.3 on 2021-05-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_services_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
