# Generated by Django 3.2.3 on 2021-05-28 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_auto_20210526_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Customer Phone Number')),
                ('address', models.CharField(max_length=150, verbose_name='Customer Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customeruser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CustomerProfile',
                'verbose_name_plural': 'CustomerProfiles',
            },
        ),
    ]
